@isTest
class globalTest{

  static testMethod void fakeTest(){
    GetProduct.fakeMethod();
    GetAccomProduct.fakeMethod();
    generateQuotePdfDocumentEFL.fakeMethod();
    generateCreditPdfDocumentAgentEFL.fakeMethod();
    generateCreditPdfDocumentStudentEFL.fakeMethod();
    generateCreditPdfDocumentStudent.fakeMethod();
    generateCreditPdfDocumentEFL.fakeMethod();
    generateQuotePdfDocumentAgentEFL.fakeMethod();
    generateQuotePdfDocumentEFL.fakeMethod();
    generateQuotePdfDocumentStudent.fakeMethod();
    generateQuotePdfDocumentStudentEFL.fakeMethod();
    
     //repeat the same for the rest of classes.
  }  
}